### ISSUE TITLE
Need to add tidy data slides

### ISSUE THREAD

**Issue by rpruim** [dtkaplan/CVC#6]
@dtkaplan, from the feedback from we have this:

Q: Can you post slides from Section 7a “how to organize your data” please? The link seems to be broken.

**Comment by nicholasjhorton** [comment]
This link currently resolves to http://cvc.mosaic-web.org/Summer2016/Learn/TidyData/tidy_data.html

**Comment by rpruim** [comment]
But there is currently no TidyData folder in this year's part of the repo.
